# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(955, 808)
        MainWindow.setStyleSheet("background:rgb(206, 177, 128)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 451, 471))
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 30, 451, 471))
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 510, 171, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 510, 171, 20))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 580, 181, 51))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("Grayscale")
        self.comboBox.addItem("HSV")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 550, 81, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 550, 31, 21))
        self.label_6.setObjectName("label_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(250, 580, 181, 51))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 550, 91, 21))
        self.label_7.setObjectName("label_7")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(520, 580, 181, 51))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(800, 550, 41, 21))
        self.label_8.setObjectName("label_8")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(730, 580, 181, 51))
        self.comboBox_4.setObjectName("comboBox_4")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(500, 510, 81, 20))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 660, 181, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 660, 181, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(520, 660, 181, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(730, 660, 181, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        #self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        #self.progressBar.setGeometry(QtCore.QRect(810, 510, 118, 23))
        #self.progressBar.setProperty("value", 24)
        #self.progressBar.setTextVisible(False)
        #self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionReset)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.comboBox_2.addItem("Convolution")
        self.comboBox_2.addItem("Averaging")
        self.comboBox_2.addItem("Median")
        self.comboBox_2.addItem("Bilateral")
        self.comboBox_2.addItem("Gaussian")
        self.comboBox_3.addItem("Binary")
        self.comboBox_3.addItem("Binary Inv")
        self.comboBox_3.addItem("Trunc")
        self.comboBox_3.addItem("Tozero")
        self.comboBox_3.addItem("Tozero Inv")
        self.comboBox_4.addItem("Laplacian")
        self.comboBox_4.addItem("SobelX")
        self.comboBox_4.addItem("SobelY")
        self.comboBox_4.addItem("ROI")
        self.comboBox.setStyleSheet("background:rgb(255, 253, 208)")
        self.comboBox_2.setStyleSheet("background:rgb(255, 253, 208)")
        self.comboBox_3.setStyleSheet("background:rgb(255, 253, 208)")
        self.comboBox_4.setStyleSheet("background:rgb(255, 253, 208)")
        self.pushButton.setStyleSheet("background:rgb(255, 253, 208)")
        self.pushButton_2.setStyleSheet("background:rgb(255, 253, 208)")
        self.pushButton_3.setStyleSheet("background:rgb(255, 253, 208)")
        self.pushButton_4.setStyleSheet("background:rgb(255, 253, 208)")
        self.label.setStyleSheet("background:rgb(255, 253, 208)")
        self.label_2.setStyleSheet("background:rgb(255, 253, 208)")
        self.menubar.setStyleSheet("background:rgb(255, 253, 208)")


        self.retranslateUi(MainWindow)
        self.comboBox.activated[str].connect(MainWindow.combo1)
        self.comboBox_2.activated[str].connect(MainWindow.combo2)
        self.comboBox_3.activated[str].connect(MainWindow.combo3)
        self.comboBox_4.activated[str].connect(MainWindow.combo4)
        self.pushButton.clicked.connect(MainWindow.rotate)
        self.pushButton_2.clicked.connect(MainWindow.translate)
        self.pushButton_3.clicked.connect(MainWindow.affinetransform)
        self.pushButton_4.clicked.connect(MainWindow.perspectivetransform)
        self.actionNew.triggered.connect(MainWindow.openfile)
        self.actionSave.triggered.connect(MainWindow.save)
        self.actionExit_2.triggered.connect(MainWindow.close)
        self.checkBox.toggled['bool'].connect(MainWindow.grid)
        self.actionReset.triggered.connect(MainWindow.reset)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Editor"))
        self.label.setText(_translate("MainWindow", " "))
        self.label_2.setText(_translate("MainWindow", " "))
        self.label_3.setText(_translate("MainWindow", ""))
        self.label_4.setText(_translate("MainWindow", ""))
        self.label_5.setText(_translate("MainWindow", "Convert Color"))
        self.label_6.setText(_translate("MainWindow", "Filter"))
        self.label_7.setText(_translate("MainWindow", "Edge Detection"))
        self.label_8.setText(_translate("MainWindow", "Other"))
        self.checkBox.setText(_translate("MainWindow", "Grid Lines"))
        self.pushButton.setText(_translate("MainWindow", "Rotate"))
        self.pushButton_2.setText(_translate("MainWindow", "Transform"))
        self.pushButton_3.setText(_translate("MainWindow", "Affine Transform"))
        self.pushButton_4.setText(_translate("MainWindow", "Perspective Transform"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
